from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models.changeKey(fromName='Model-1',toName='p111')
mdb.models['p111'].ConstrainedSketch(name='__profile__', sheetSize=1200.0)
mdb.models['p111'].sketches['__profile__'].Line(point1=(-153.729, 97.9931), point2=(-127.7482, 82.9931))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-127.7482, 82.9931), point2=(-126.1328, 82.3074))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-126.1328, 82.3074), point2=(-124.3995, 82.0328))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-124.3995, 82.0328), point2=(-122.6512, 82.1858))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-122.6512, 82.1858), point2=(-120.9919, 82.7571))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-120.9919, 82.7571), point2=(-119.5201, 83.7129))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-119.5201, 83.7129), point2=(-61.3404, 132.5315))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-61.3404, 132.5315), point2=(-57.2772, 135.4836))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-57.2772, 135.4836), point2=(-52.8426, 137.8415))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-52.8426, 137.8415), point2=(-48.123, 139.5593))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-48.123, 139.5593), point2=(-43.2103, 140.6035))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-43.2103, 140.6035), point2=(-38.2001, 140.9539))
mdb.models['p111'].sketches['__profile__'].Line(point1=(-38.2001, 140.9539), point2=(38.2001, 140.9539))
mdb.models['p111'].sketches['__profile__'].Line(point1=(38.2001, 140.9539), point2=(43.2103, 140.6035))
mdb.models['p111'].sketches['__profile__'].Line(point1=(43.2103, 140.6035), point2=(48.123, 139.5593))
mdb.models['p111'].sketches['__profile__'].Line(point1=(48.123, 139.5593), point2=(52.8426, 137.8415))
mdb.models['p111'].sketches['__profile__'].Line(point1=(52.8426, 137.8415), point2=(57.2772, 135.4836))
mdb.models['p111'].sketches['__profile__'].Line(point1=(57.2772, 135.4836), point2=(61.3404, 132.5315))
mdb.models['p111'].sketches['__profile__'].Line(point1=(61.3404, 132.5315), point2=(119.5201, 83.7129))
mdb.models['p111'].sketches['__profile__'].Line(point1=(119.5201, 83.7129), point2=(120.9919, 82.7571))
mdb.models['p111'].sketches['__profile__'].Line(point1=(120.9919, 82.7571), point2=(122.6512, 82.1858))
mdb.models['p111'].sketches['__profile__'].Line(point1=(122.6512, 82.1858), point2=(124.3995, 82.0328))
mdb.models['p111'].sketches['__profile__'].Line(point1=(124.3995, 82.0328), point2=(126.1328, 82.3074))
mdb.models['p111'].sketches['__profile__'].Line(point1=(126.1328, 82.3074), point2=(127.7482, 82.9931))
mdb.models['p111'].sketches['__profile__'].Line(point1=(127.7482, 82.9931), point2=(153.729, 97.9931))
mdb.models['p111'].Part(dimensionality=THREE_D, name='sector', type=DEFORMABLE_BODY)
mdb.models['p111'].parts['sector'].BaseShellExtrude(depth=1200.0, sketch=mdb.models['p111'].sketches['__profile__'])
del mdb.models['p111'].sketches['__profile__']
mdb.models['p111'].Material(name='pure-elastic')
mdb.models['p111'].materials['pure-elastic'].Elastic(table=((210000.0, 0.3), ))